language: node_js
node_js:
  - "6"
install:
  - npm install
branches:
  only:
  - master
before_script:
  - npm run lint
script: gulp
deploy:
  provider: heroku
  app: super-photo-quest  
  api_key:
    secure: Qvmw5T5fcScokVCywryxzaQW5dcW0gIuY1+yO2tFbMBpaoOKsfkxxzETkkvOb/Ka8WrwnPfgLRMED8lRsusPQZLfCwimdvAYEAgqhOYND8hjUXBOVrg+a80eiu/XTL92KIvrVvyPYuozVeJ3KKU6pCzuAE7s/dH5+WzruAV4lZAmNJTL9ml+I8ugBPoVJrY5WpM/U8ZFjihJOopkWa/aGkWDMZ9bz1LZgXtiQggR1qPqwNUJE07yJbTVakjqE1cLyncoNNXTlPOXCnke6EeCmLtq9A7Mj/rBglRWlDc2w7T45Z7PrAN6s8ihEX2za2kRm/naTyADT4/98gF0SVBlsROe6ZBOa9rxMD4IyzD67xh3q4dB02KILjMZJfFkt9Qhjl3sbjeinjhfmvKayo7IJ+qw7UCIDiGBfRJgCmWzjqUFiSZVEqz9JvFOdGFj3tbEgcqTjk6NG417j6vklvPtqOBrXBs6w/2D5xDqmskewPkUJK7zI1AS+dAzcyWFqZE9s+7gvFtALhZz82DHBSir546TETKr2wXiYvLT3FRveDyPZCkN3EsmhE+d8XKNbN/dMTy606mHQ4hfg1AgN10iqzFcONTMNZGPTqIscCDVY1cm4jJojA1Qp4+PQQzuD69M/dj7B6do6dMHEP2a9REb1wO5exvrY3LzTF7v1+95S5s=
  on:
    repo: urfu-2016/team4
