language: node_js
node_js:
- '6'
install:
- npm install
branches:
  only:
  - master
before_script:
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: pGnrJ92lrvHyIvhJN0Lnw/UVnenrLkied7krwq40tr66+NZG0CFbzsYhrT1/4iqrbcYeSkB221A8C2j6XuIAKpY1ItNkbPOOd74jbVpf6NW40RMq/yylQd3iyxIYFA+khYkF53sGv7Z2hYeZbDCOsXCrvDIT+PbYc4TpEJ7SZgJai7E0S6pDUj+abnxUHugULOF+T8hV/X4kTdgA/EkkqvDXZiuO4GUeClXpjeCHObv+4jJl53MZJqnkze6oxFLAl55Rgpxozcyq8WBrxqp9tNGWPzevNFK1qu4o6LxlAPZ1BZP1Y42HCZe7jrTSj0rBPH3sXuwJ7/V7NyUUK7UnwMSivjNB8cYPRiR/RphP4oljWuHk8iwCzmxhEUFQFrJFMi4ZeYb0BxUKXekDZckY2Rsl6zX+l2A0P2gfErOhykvMWIlrDRBxoAlp20DviK3k0rGrJ7VcwU7vpJwY8TZzY8Dqpdn31NOctyBnQ95MF8bLzWmJ+3H3uEquYoxdYToc20lVBjdS6he4qzTgh3pT03Jg4lUEkJc7kSX8zm+UsbJJmqEDC2JrSRX9b11syOQkyjLGBaV3aP953YN4DsMG6EDdealFs9zCrWkLnbMhncecdpsBVESO39dMIPNW6cv+u5UHM1/l9wYY6e3WC7s1ar4RerQ4rmCEVq3m5Wa2x+I=
  app: super-photo-quest
  on:
    repo: urfu-2016/team4
after_success:
- '["${TRAVIS_PULL_REQUEST}" = "false"] && npm run surge'
